kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
     - containerPort: 30002
       hostPort: 30002
- role: worker
  extraPortMappings:
    - containerPort: 30002
      hostPort: 30003
- role: worker
  extraPortMappings:
    - containerPort: 30002
      hostPort: 30004
